version: '2'

services:
  web:
    build: .
    command: 'bash -c ''bin/server'''
    working_dir: /app/user
    environment:
      PORT: 8080
      DATABASE_URL: 'postgres://db:5432/postgres'
    ports:
      - '8080:8080'
    volumes:
      - '.:/app/user'
  db:
    image: postgres
